// Generated by scripts/register-lessons.mjs from individually reviewed lesson files.
import type { Topic } from './types';
import lesson0 from './lessons/special-relativity.json' with { type: 'json' };
export const additions: Topic[] = [lesson0] as unknown as Topic[];
