// Generated by scripts/register-lessons.mjs from individually reviewed lesson files.
import type { Topic } from './types';
import lesson0 from './lessons/black-holes.json' with { type: 'json' };
import lesson1 from './lessons/general-relativity.json' with { type: 'json' };
import lesson2 from './lessons/special-relativity.json' with { type: 'json' };
export const additions: Topic[] = [lesson0, lesson1, lesson2] as unknown as Topic[];
