import { readdirSync, writeFileSync } from 'node:fs';
const files=readdirSync('content/lessons').filter(f=>f.endsWith('.json')).sort();
const imports=files.map((f,i)=>`import lesson${i} from './lessons/${f}' with { type: 'json' };`).join('\n');
writeFileSync('content/additions.ts',`// Generated by scripts/register-lessons.mjs from individually reviewed lesson files.\nimport type { Topic } from './types';\n${imports}\nexport const additions: Topic[] = [${files.map((f,i)=>`lesson${i}`).join(', ')}] as unknown as Topic[];\n`);
